### ISSUE TITLE
Internal dependency update (debug-ids 1.0.2, integration 6.1.1) lead to crash accessing "styles"

### ISSUE THREAD

**Issue by swernerx** [vanilla-extract-css/vanilla-extract#1027]
### Describe the bug

Our project is a mono-repo with a shared UI library and different apps. When re-building our pnpm lock file the following changes are applied to the repo:

```
diff --git a/pnpm-lock.yaml b/pnpm-lock.yaml
index 1a7e909..58ed352 100644
--- a/pnpm-lock.yaml
+++ b/pnpm-lock.yaml
@@ -872,7 +872,7 @@ packages:
       '@babel/core': ^7.0.0-0
     dependencies:
       '@babel/core': 7.12.9
-      '@babel/helper-plugin-utils': 7.20.2
+      '@babel/helper-plugin-utils': 7.10.4
       '@babel/plugin-syntax-object-rest-spread': 7.8.3_@babel+core@7.12.9
       '@babel/plugin-transform-parameters': 7.20.7_@babel+core@7.12.9
 
@@ -6284,8 +6284,8 @@ packages:
       eslint-visitor-keys: 3.3.0
     dev: false
 
-  /@vanilla-extract/babel-plugin-debug-ids/1.0.1:
-    resolution: {integrity: sha512-ynyKqsJiMzM1/yiIJ6QdqpWKlK4IMJJWREpPtaemZrE1xG1B4E/Nfa6YazuDWjDkCJC1tRIpEGnVs+pMIjUxyw==}
+  /@vanilla-extract/babel-plugin-debug-ids/1.0.2:
+    resolution: {integrity: sha512-LjnbQWGeMwaydmovx8jWUR8BxLtLiPyq0xz5C8G5OvFhsuJxvavLdrBHNNizvr1dq7/3qZGlPv0znsvU4P44YA==}
     dependencies:
       '@babel/core': 7.21.0
     transitivePeerDependencies:
@@ -6306,12 +6306,12 @@ packages:
       media-query-parser: 2.0.2
       outdent: 0.8.0
 
-  /@vanilla-extract/integration/6.1.0:
-    resolution: {integrity: sha512-7gDkOibk/DraG35ZpiAYqWd33wLA6YRnieC5vw7ItoFEzCv9bUaS9c+ZyktyWW3nRnL+e7Pc6FS6l7MKgEsX1w==}
+  /@vanilla-extract/integration/6.1.1:
+    resolution: {integrity: sha512-JGlynmtCju+NWU5ITgs81szCo8A4hFfW1E2oAsn++JHvgU7+wyg9N0TwByZOB1/nbrHVKISzRvl1M0BeB0mZXQ==}
     dependencies:
       '@babel/core': 7.21.0
       '@babel/plugin-syntax-typescript': 7.20.0_@babel+core@7.21.0
-      '@vanilla-extract/babel-plugin-debug-ids': 1.0.1
+      '@vanilla-extract/babel-plugin-debug-ids': 1.0.2
       '@vanilla-extract/css': 1.9.5
       esbuild: 0.16.17
       eval: 0.1.6
@@ -6326,7 +6326,7 @@ packages:
   /@vanilla-extract/jest-transform/1.1.0:
     resolution: {integrity: sha512-yjk/IXMOGrvFXW48eF/JmMua/KumbT8HI1OtCHfod4MFiJq9F7i0qF+UCoNwAMTwywu0eFWnHbTU/3jd8phUjA==}
     dependencies:
-      '@vanilla-extract/integration': 6.1.0
+      '@vanilla-extract/integration': 6.1.1
       esbuild: 0.16.17
     transitivePeerDependencies:
       - supports-color
@@ -6348,7 +6348,7 @@ packages:
     peerDependencies:
       vite: ^2.2.3 || ^3.0.0 || ^4.0.3
     dependencies:
-      '@vanilla-extract/integration': 6.1.0
+      '@vanilla-extract/integration': 6.1.1
       outdent: 0.8.0
       postcss: 8.4.21
       postcss-load-config: 3.1.4_postcss@8.4.21
@@ -6363,7 +6363,7 @@ packages:
     peerDependencies:
       webpack: ^4.30.0 || ^5.20.2
     dependencies:
-      '@vanilla-extract/integration': 6.1.0
+      '@vanilla-extract/integration': 6.1.1
       chalk: 4.1.2
       debug: 4.3.4
       loader-utils: 2.0.4
````

As soon as these changes have been applied the following crash happens somewhere during our call to create sprinkles:

```
react.development.js:1407 Uncaught TypeError: Cannot read properties of undefined (reading 'styles')
    at createSprinkles-29d354c5.esm.js:47:62
    at Array.map (<anonymous>)
    at createSprinkles-29d354c5.esm.js:47:51
    at createSprinkles3 (vanilla-extract-sprinkles-createRuntimeSprinkles.esm.js:6:41)
    at Text.css.ts:3:24
```

This is the line which crashes:

```
  var sprinklesStyles = Object.assign({}, ...args.map(a => a.styles));
````

inside of this block:

```
var createSprinkles = composeStyles => function () {
  for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
    args[_key] = arguments[_key];
  }

  var sprinklesStyles = Object.assign({}, ...args.map(a => a.styles));
  var sprinklesKeys = Object.keys(sprinklesStyles);
  var shorthandNames = sprinklesKeys.filter(property => 'mappings' in sprinklesStyles[property]);
```

That's what we are doing:

```
import { createSprinkles, defineProperties } from "@vanilla-extract/sprinkles"

import { fontSizes, fontWeights, letterSpacings, lineHeights } from "./styles"

export const textProperties = defineProperties({
  properties: {
    fontSize: fontSizes,
    fontWeight: fontWeights,
    letterSpacing: letterSpacings,
    lineHeight: lineHeights
  }
})

export const textAtoms = createSprinkles(textProperties)
```

Anybody has an idea what happens here. From what I see in the repo it's not obvious to me. Thanks for any help!

### Reproduction

working on it

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (20) arm64 Apple M1 Ultra
    Memory: 1.47 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /opt/homebrew/opt/node@16/bin/node
    npm: 8.19.3 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 109.0.1
    Safari: 16.3
  npmPackages:
    @vanilla-extract/css: ^1.9.5 => 1.9.5
    @vanilla-extract/jest-transform: ^1.1.0 => 1.1.0
    @vanilla-extract/sprinkles: ^1.5.1 => 1.5.1
    @vanilla-extract/vite-plugin: ^3.8.0 => 3.8.0
    vite: ^4.1.4 => 4.1.4
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
I think the likely culprit is integration 6.1.1. I've made a reproduction [here](https://github.com/askoufis/vanilla-extract-issue-1027-repro).
