### ISSUE TITLE
[@vanilla-extract/webpack-plugin] Error: Didn't get a result from child compiler

### ISSUE THREAD

**Issue by KotoriK** [vanilla-extract-css/vanilla-extract#1069]
## Brief
```Error: Didn't get a result from child compiler``` will be thrown when ```@vanilla-extract/webpack-plugin``` is trying to parse a file under a folder which has a name with character "[]". 
This is a naming convention in some frameworks for dynamic routing, eg. [Next.js](https://beta.nextjs.org/docs/routing/defining-routes#example).
Thus for now, a vanilla-extract style file placed under a dynamic route folder like this won't work properly. 
## Reproduce Link
This is a webpack spa sample project which simulate the problem. 
https://github.com/KotoriK/vanilla-extract-webpack-resolve

### Reproduction

https://github.com/KotoriK/vanilla-extract-webpack-resolve

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 18.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.48)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vanilla-extract/css: ^1.11.0 => 1.11.0
    @vanilla-extract/webpack-plugin: ^2.2.0 => 2.2.0
    webpack: ^5.79.0 => 5.79.0
```

### Used Package Manager

pnpm

### Logs

```shell
ERROR in ./src/[id]/broken.css.js
Module build failed (from ./node_modules/.pnpm/@vanilla-extract+webpack-plugin@2.2.0_webpack@5.79.0/node_modules/@vanilla-extract/webpack-plugin/loader/dist/vanilla-extract-webpack-plugin-loader.cjs.js):
Error: Didn't get a result from child compiler
    at \home\vanilla-extract-webpack-resolve\node_modules\.pnpm\@vanilla-extract+webpack-plugin@2.2.0_webpack@5.79.0\node_modules\@vanilla-extract\webpack-plugin\dist\vanilla-extract-webpack-plugin.cjs.dev.js:167:25
    at finalCallback (\home\vanilla-extract-webpack-resolve\node_modules\.pnpm\webpack@5.79.0_webpack-cli@5.0.1\node_modules\webpack\lib\Compiler.js:551:5)
    at \home\vanilla-extract-webpack-resolve\node_modules\.pnpm\webpack@5.79.0_webpack-cli@5.0.1\node_modules\webpack\lib\Compiler.js:577:11
    at \home\vanilla-extract-webpack-resolve\node_modules\.pnpm\webpack@5.79.0_webpack-cli@5.0.1\node_modules\webpack\lib\Compiler.js:1199:17
    at Hook.eval [as callAsync] (eval at create (\home\vanilla-extract-webpack-resolve\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (\home\vanilla-extract-webpack-resolve\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\Hook.js:18:14)
    at \home\vanilla-extract-webpack-resolve\node_modules\.pnpm\webpack@5.79.0_webpack-cli@5.0.1\node_modules\webpack\lib\Compiler.js:1195:33
    at finalCallback (\home\vanilla-extract-webpack-resolve\node_modules\.pnpm\webpack@5.79.0_webpack-cli@5.0.1\node_modules\webpack\lib\Compilation.js:2787:11)
    at \home\vanilla-extract-webpack-resolve\node_modules\.pnpm\webpack@5.79.0_webpack-cli@5.0.1\node_modules\webpack\lib\Compilation.js:3092:11
    at Hook.eval [as callAsync] (eval at create (\home\vanilla-extract-webpack-resolve\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (\home\vanilla-extract-webpack-resolve\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\Hook.js:18:14)
    at \home\vanilla-extract-webpack-resolve\node_modules\.pnpm\webpack@5.79.0_webpack-cli@5.0.1\node_modules\webpack\lib\Compilation.js:3085:38
    at eval (eval at create (\home\vanilla-extract-webpack-resolve\node_modules\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:17:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:442:9)
 @ ./src/[id]/Broken.jsx 1:0-36 4:15-19
 @ ./src/index.js 3:0-35 7:48-54
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by samzhangjy** [comment]
It's been almost six months since this issue has been submitted, any updates on this? I'm still experiencing the same error with `@vanilla-extract/css^1.11.1` and `@vanilla-extract/next-plugin^2.3.1`.

**Comment by KysawaJR** [comment]
estou tendo o mesmo problema, estou desenvolvendo um E-commerce para meu cliente, utilizando Next.js 14 e Vanilla Extract. 
na pagina inicial ocorre tudo bem, mas basta mudar de página e é exibido este erro, trava o site inteiro...
