### ISSUE TITLE
"ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered" after adding withVanillaExtract to next.config.js

### ISSUE THREAD

**Issue by olalonde** [vanilla-extract-css/vanilla-extract#1182]
### Describe the bug

```
$ npm run dev 

> web@0.0.0 dev
> next dev

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
Error: ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered
    at Object.register (/Users/redacted/code/proj/apps/web/node_modules/next/dist/compiled/webpack/bundle5.js:28:1192877)
    at MiniCssExtractPlugin.getCssModule (/Users/redacted/code/proj/node_modules/next/dist/compiled/mini-css-extract-plugin/index.js:1:7516)
    at NextMiniCssExtractPlugin.apply (/Users/redacted/code/proj/node_modules/next/dist/compiled/mini-css-extract-plugin/index.js:1:10311)

```

next.config.js

```js
const { createVanillaExtractPlugin } = require('@vanilla-extract/next-plugin');
const withVanillaExtract = createVanillaExtractPlugin();

/** @type {import('next').NextConfig} */
const nextConfig = {
  // reactStrictMode: false,
  reactStrictMode: true,
  swcMinify: true,
  eslint: {
    ignoreDuringBuilds: true,
  },
};

module.exports = withVanillaExtract(nextConfig);
```

### Reproduction

See aboive

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 779.94 MB / 16.00 GB
    Shell: 5.8 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 20.5.0 - ~/Library/Caches/fnm_multishells/70155_1694527768381/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/70155_1694527768381/bin/yarn
    npm: 9.8.0 - ~/Library/Caches/fnm_multishells/70155_1694527768381/bin/npm
    pnpm: 7.30.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.5
```
```


### Used Package Manager

npm

### Logs

```shell
See above
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
@olalonde I can't reproduce your issue in a simple next app using the config you provided. Please provide a full reproduction so we can attempt to diagnose the problem. Also, please ensure you're using the latest version of the next plugin.

**Comment by syfxlin** [comment]
I ran into this issue a while back, probably due to multiple versions of Next.js being installed, causing @vanilla-extract/next-plugin to duplicate adding the MiniCssExtractPlugin to webpack.

You can check if multiple versions of Next.js exist with the following command:
```shell
npm list --all | grep next@
```

**Comment by olalonde** [comment]
The issues went away when i moved the project out of a npm workspace and into a standalone project.

**Comment by askoufis** [comment]
Seems like maybe [the `instanceof` check in the next plugin](https://github.com/vanilla-extract-css/vanilla-extract/blob/af00b356dd323af2a8a03c16a79506a2857fd8ae/packages/next-plugin/src/index.ts#L160) isn't effective.

**Comment by steadily-worked** [comment]
i ran into the same error using Turborepo, this issue went away when i upgraded Next.js version all at the same time

before(this issue appeared)
- web: ^14.0.1
- docs: ^13.4.19
- ui: ^13.4.19

after(this issue went away)
- web: ^14.0.1
- docs: ^14.0.1
- ui: ^14.0.1

**Comment by askoufis** [comment]
Seems like this was probably a project configuration issue. @olalonde Since you've fixed the problem, I'm going to close the issue. Please re-open if it's still a problem.
