### ISSUE TITLE
Vanilla Extract files from component library won't build in dev server (Remix)

### ISSUE THREAD

**Issue by brandonpittman** [vanilla-extract-css/vanilla-extract#1226]
### Describe the bug

A component library that consumes VE styles builds correctly in dev, but errors in dev.

Example repo: https://github.com/brandonpittman/ve-mitosis-library

The repo has vars and sprinkles for VE. The components are written with Builder's Mitosis library and compiled to Qwik and React components. The repo has a docs page that can be built with `npm run dev`. When building the docs page for prod with `npm run build`, I get the `css.ts` context error.

### Reproduction

https://github.com/brandonpittman/ve-mitosis-library

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 114.67 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.18.0 - ~/Library/pnpm/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 9.8.1 - ~/Library/pnpm/npm
    pnpm: 7.9.5 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 119.0.6045.123
    Firefox Nightly: 107.0a1
    Safari: 17.0
```

### Used Package Manager

npm

### Logs

```shell
error during build:
Error: Styles were unable to be assigned to a file. This is generally caused by one of the following:

- You may have created styles outside of a '.css.ts' context
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/getting-started
    at Object.getFileScope (/Users/blp/Developer/pneuma-share/node_modules/@vanilla-extract/css/fileScope/dist/vanilla-extract-css-fileScope.cjs.prod.js:35:11)
    at createGlobalTheme (/Users/blp/Developer/pneuma-share/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.prod.js:319:48)
    at file:///Users/blp/Developer/pneuma-share/packages/docs/server/assets/entry.ssr-7f894bdb.js:262:22084
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
Getting some errors when trying to run `npm run dev` in the docs package. I think you need to declare some more dependencies on your scoped packages.

**Comment by brandonpittman** [comment]
> Getting some errors when trying to run `npm run dev` in the docs package. I think you need to declare some more dependencies on your scoped packages.

@askoufis What's the error? I'm not seeing any.

**Comment by askoufis** [comment]
I ran:
- `npm install`
- `cd packages/docs`
- `nr dev`

Seeing this:
```
Error:   Failed to scan for dependencies from entries:
  /Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/packages/docs/src/entry.ssr.tsx

  ✘ [ERROR] Failed to resolve entry for package "@scoped-example/qwik". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    ../../node_modules/vite/node_modules/esbuild/lib/main.js:1373:21:
      1373 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28725:11)
    at resolvePackageEntry (file:///Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28722:5)
    at tryNodeResolve (file:///Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28453:20)
    at Context.resolveId (file:///Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28212:28)
    at Object.resolveId (file:///Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44276:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44581:26)
    at async file:///Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44758:34
    at async requestCallbacks.on-resolve (/Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:1373:22)
    at async handleRequest (/Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:729:13)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/vite/node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44748:19)
    at handlePlugins (/Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:1292:21)
    at buildOrContextImpl (/Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:978:5)
    at Object.buildOrContext (/Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:786:5)
    at /Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (/Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:2186:27)
    at Object.context (/Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:2026:58)
    at prepareEsbuildScanner (file:///Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44531:26)

  The plugin "vite:dep-scan" was triggered by this import

    src/root.tsx:8:23:
      8 │ import { Button } from "@scoped-example/qwik";
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~


    at failureErrorWithLog (/Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (/Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:1484:45)
    at buildResponseToResult (/Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:1056:7)
    at /Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:1068:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:1067:54)
    at handleRequest (/Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:729:19)
    at handleIncomingPacket (/Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:755:7)
    at Socket.readFromStdout (/Users/askoufis/code/vanilla-extract-css/issues/1226/ve-mitosis-library/node_modules/vite/node_modules/esbuild/lib/main.js:679:7)
```

**Comment by brandonpittman** [comment]
@askoufis 

Maybe it was because I didn't have the `patch-package` postinstall script in there. Just pushed a change.

VE doesn't recognize `qwik.mjs` files, which Qwik requires. I patched the dev CSS filter for VE to accept `css.qwik.mjs` files. It's in the repo now. Should build.

**Comment by askoufis** [comment]
That doesn't seem to have fixed it. Vite is complaining about not being able to scan for dependencies because your `docs` packages hasn't declared a dependency on `@scoped-example/qwik` yet it uses it in `src/root.tsx`.

**Comment by brandonpittman** [comment]
@askoufis Can you tell me how to declare a dependency for a workspace inside a project? I Googled for something like that, but didn't find it. Thought it would just work since it's a workspace declared in the root.

I'm not seeing that error when I run `npm run dev` either. 😢

**Comment by askoufis** [comment]
You can just add the package as a dependency. NPM should just figure out that you're referencing a workspace package and prefer that instead of fetching it from the registry.

**Comment by brandonpittman** [comment]
@askoufis Pushed a change. No difference in my output.

**Comment by askoufis** [comment]
The dev server at least starts now, but getting a new error:

```
Failed to resolve entry for package "@scoped-example/vanilla-extract". The package may have incorrect main/module/exports specified in its package.json.
```

**Comment by brandonpittman** [comment]
@askoufis Added explicit exports declaration for the ve package.

I wonder why this all just worked for me (without explicit declaration) but not for you. 🤔

**Comment by askoufis** [comment]
Still getting the same error. Really struggling to understand why it's working for you. Do you have some packages installed globally? Have you started with a clean `node_modules`? Could you try deleting a re-cloning the repo?

**Comment by brandonpittman** [comment]
@askoufis 

Deleted the repo, cloned it, and the same errors you saw started. Will fix and push. Thanks for your patience.

**Comment by brandonpittman** [comment]
@askoufis 

Ah! The `exports` key is referencing the `dist` build files, so without an initial build, the `exports` files aren't there.

**Comment by askoufis** [comment]
After some debugging, it looks like the issue is those `.qwik.` files. Even though you've patched VE, there's probably some more work needed to support those files. That being said, I'm not sure if it should be on Vanilla Extract to support those files in the first place, but instead something that `mitosis` needs to handle. Qwik itself supports vanilla extract, but I guess this component meta-framework doesn't.

Dev mode likely works because it's not depending on built files, instead using source code directly.

**Comment by brandonpittman** [comment]
I don't see how it can be Mitosis. Mitosis just spits out JSX files and it runs as a CLI command and not part of Vite's build process.

**Comment by askoufis** [comment]
> I don't see how it can be Mitosis. Mitosis just spits out JSX files and it runs as a CLI command and not part of Vite's build process.

But your docs app references the `Button` component from your `ui` package, which means it loads `atoms.css.ts` from your `vanilla-extract` package, finally resulting in a `atoms.css.qwik.mjs` file, which eventually calls `globalStyle`, which throws the error.

**Comment by brandonpittman** [comment]
> > I don't see how it can be Mitosis. Mitosis just spits out JSX files and it runs as a CLI command and not part of Vite's build process.
> 
> But your docs app references the `Button` component from your `ui` package, which means it loads `atoms.css.ts` from your `vanilla-extract` package, finally resulting in a `atoms.css.qwik.mjs` file, which eventually calls `globalStyle`, which throws the error.

@askoufis and because I patched that, it doesn’t throw in dev? That makes sense. 

When it errors in the prod build, it happens in a entry.server-xxx.js file with a different pattern. I patched that pattern into the prod filter but it had no effect.

**Comment by brandonpittman** [comment]
@askoufis 

Maybe Qwik is just weird. If I could find a React component library built on VE and Vite I think I could figure a way to make Qwik work.

**Comment by brandonpittman** [comment]
@askoufis Maybe I have a fundamental misunderstanding of what's possible…

1. My hope was that I could export components that called functions that the consuming app's VE would pick up. I'm running into all kinds of problems.
2. If I build the Qwik library using the Vite VE plugin, I get components with baked-in class names and a bundle CSS file that can be imported in a consuming app.

Is #1 just not a possibility and #2 is the only way to build a component library with VE?

**Comment by askoufis** [comment]
1 should be possible. The idea being that you don't do anything to your `css.ts` files other than convert them to `css.js/cjs/mjs` files. Mitosis _is_ adding its own extension, which is IMO the cause of the issue.

2 is also viable, though ideally you'd enable something like `preserveModules` so that each component ends up with its own CSS file that it imports.

I've seen both methods done before. The difference here seems to be `mitosis`. Since you're generating both `qwik` and `react` components, my guess is that the `react` components will work just fine.

**Comment by brandonpittman** [comment]
@askoufis Thanks for all your time. We seem to be going in circles so I'm going to close this issue.

**Comment by brandonpittman** [comment]
So…by making `@scoped-example/vanilla-extract` external in the Qwik `vite.config.ts`, all the Qwik stuff works—and I was able to remove the patch!

Still having trouble importing the components into a Remix project though. Getting a `.css.ts` error on `vars.css.ts?used` in the dev server for Remix. Will debug a little more, but all the Qwik stuff is working. 😄

**Comment by brandonpittman** [comment]
If I re-export my sprinkles function from a local `sprinkles.css.ts` file, things work, but importing directly from the package creates the above error as well.

**Comment by brandonpittman** [comment]
Working in non-Remix React app. Must be something funny about Remix.
