### ISSUE TITLE
Conflicts with @sentry/vite-plugin in yarn workspaces when using Remix

### ISSUE THREAD

**Issue by MattyBalaam** [vanilla-extract-css/vanilla-extract#1329]
### Describe the bug

I am unsure if this would be related to this package or could be an issue with the Sentry plugin or Remix, but they fail to build when used together in a workspace in a yarn monorepo (yarn dev or yarn build).  

I have been able to use Sentry and Vanilla together in a plain project (see the `/non-remix` example which works) 

Running in a non mono repo works as expected. I have added an example repo. 

<img width="919" alt="Screenshot 2024-02-22 at 09 12 48" src="https://github.com/vanilla-extract-css/vanilla-extract/assets/1246923/a56b94d4-90c1-4a1a-9376-0315676a2e91">

### Reproduction

https://github.com/MattyBalaam/vite-remix-vanilla-sentry

- `$ cd remix-app`
- `$ yarn dev` (or `build`)

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 57.25 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 4.1.0 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - /opt/homebrew/opt/node@18/bin/npm
  Browsers:
    Chrome: 122.0.6261.57
    Safari: 17.3.1
  npmPackages:
    @vanilla-extract/vite-plugin: 4.0.4 => 4.0.4 
    vite: 5.1.0 => 5.1.0
```

### Used Package Manager

yarn

### Logs

```shell
TypeError: [vanilla-extract] Cannot read properties of undefined (reading 'remixConfig')
file: /Users/mbalaam/remix-vite-sentry-vanilla/remix-app/app/components/test.css.ts
    at TransformContext.transform (/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/dev/dist/vite/plugin.js:890:32)
    at Object.transform (file:///Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@vanilla-extract/vite-plugin/node_modules/@vanilla-extract/integration/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:50838:62)
    at async loadAndTransform (file:///Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@vanilla-extract/vite-plugin/node_modules/@vanilla-extract/integration/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:53611:29)
    at async ViteNodeServer._transformRequest (file:///Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/vite-node/dist/server.mjs:409:16)
    at async ViteNodeServer._fetchModule (file:///Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/vite-node/dist/server.mjs:379:17)
    at async ViteNodeRunnerWithContext.directRequest (file:///Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/vite-node/dist/client.mjs:250:46)
    at async ViteNodeRunnerWithContext.cachedRequest (file:///Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/vite-node/dist/client.mjs:189:14)
    at async ViteNodeRunnerWithContext.dependencyRequest (file:///Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/vite-node/dist/client.mjs:233:12)
    at async /Users/mbalaam/remix-vite-sentry-vanilla/remix-app/app/components/test.css.ts:4:31
    at async ViteNodeRunnerWithContext.runModule (file:///Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/vite-node/dist/client.mjs:362:5) {
  plugin: 'vanilla-extract',
  id: '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/app/components/test.css.ts',
  pluginCode: '\n' +
    '    var _global =\n' +
    "      typeof window !== 'undefined' ?\n" +
    '        window :\n' +
    "        typeof global !== 'undefined' ?\n" +
    '          global :\n' +
    "          typeof self !== 'undefined' ?\n" +
    '            self :\n' +
    '            {};\n' +
    '\n' +
    '    _global.SENTRY_RELEASE={id:"9bca35f332525602684ae66621b0020e340b0404"};',
  code: 'PLUGIN_ERROR',
  hook: 'transform',
  watchFiles: [
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/app/root.tsx',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/app/routes/_index.tsx',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/dev/dist/config/defaults/entry.client.tsx',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/package.json',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/react/jsx-runtime.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/react/dist/esm/index.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/react/index.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/react-dom/client.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/react/dist/esm/browser.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/react/dist/esm/scroll-restoration.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/react/dist/esm/components.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/react/dist/esm/server.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/index.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/react-router-dom/dist/index.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/app/components/test.tsx',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/react/cjs/react-jsx-runtime.production.min.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/react/cjs/react.production.min.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/react-dom/index.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/cookies.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/formData.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/react/dist/esm/errorBoundaries.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/react/dist/esm/routes.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/react-router-dom/server.mjs',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/react/dist/esm/_virtual/_rollupPluginBabelHelpers.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/responses.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/sessions/memoryStorage.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/upload/memoryUploadHandler.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/upload/errors.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/server.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/dev.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/sessions.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/sessions/cookieStorage.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/react/dist/esm/errors.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/router/dist/router.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/react-router/dist/index.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/warnings.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/node_modules/cookie/index.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/react/dist/esm/routeModules.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/react/dist/esm/invariant.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/react/dist/esm/fallback.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@web3-storage/multipart-parser/esm/src/index.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/entry.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/headers.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/errors.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/react/dist/esm/links.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/routeMatching.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/routes.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/mode.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/invariant.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/serverHandoff.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/react/dist/esm/data.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/set-cookie-parser/lib/set-cookie.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/data.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/server-runtime/dist/esm/markup.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@web3-storage/multipart-parser/esm/src/search.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@web3-storage/multipart-parser/esm/src/utils.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/@remix-run/react/dist/esm/markup.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/react-dom/cjs/react-dom.production.min.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/app/components/test.css.ts',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/scheduler/index.js',
    '/Users/mbalaam/remix-vite-sentry-vanilla/remix-app/node_modules/scheduler/cjs/scheduler.production.min.js'
  ]
}
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MattyBalaam** [comment]
Doing a bit of digging I have been able to brute-force fix it if I change `remix-route-exports` in the remixVitePlugin to test that ctx exists…
 
<img width="572" alt="Screenshot 2024-02-23 at 10 05 05" src="https://github.com/vanilla-extract-css/vanilla-extract/assets/1246923/05da8c25-fbd2-429b-aa95-c0276784e4c3">

I’m not sure why ctx does not exist in this case though…

**Comment by askoufis** [comment]
Thanks for raising this issue @MattyBalaam.

It seems like [sentry's release injection plugin](https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/bbe047289daeb2373ed29c1fdd264927668ac4e4/packages/bundler-plugin-core/src/index.ts#L369) is somehow triggering [the `remix-route-exports` plugin](https://github.com/remix-run/remix/blob/a2f2e68b520ffad91112bc0967470b2ad9ccf80c/packages/remix-dev/vite/plugin.ts#L1437) during an SSR load, but without `options.ssr: true` being set, which would ordinarily skip the `transform` callback, and since [we filter out the main `remix` plugin](https://github.com/vanilla-extract-css/vanilla-extract/blob/d11976cbbf930a369eb8158c1a2a760e0727f7b5/packages/vite-plugin/src/index.ts#L146), `ctx` is never [initialized](https://github.com/remix-run/remix/blob/a2f2e68b520ffad91112bc0967470b2ad9ccf80c/packages/remix-dev/vite/plugin.ts#L911), causing this error.

I feel like the easiest fix here is to either filter all `remix*` plugins, or filter all `sentry` plugins, or both. Thoughts @mrm007?

**Comment by gorjs3540** [comment]
The same problem is happening with a single project consisting of remix, vanillia-extract, vite, and sentry. Is this issue expected to be delayed a lot?

**Comment by askoufis** [comment]
This issue should be fixed by https://github.com/vanilla-extract-css/vanilla-extract/pull/1369. Please try out this snapshot version of the vite plugin if you get a chance: `@vanilla-extract/vite-plugin@0.0.0-fix-vite-bugs-20240323060142`.

**Comment by MattyBalaam** [comment]
Thanks, I’ll test this on Monday.

**Comment by MattyBalaam** [comment]
@askoufis tested and working 👍
