### ISSUE TITLE
Cannot build a next app with Turbopack (Styles were unable to be assigned to a file)

### ISSUE THREAD

**Issue by nicolassanmar** [vanilla-extract-css/vanilla-extract#1367]
### Describe the bug

I'm trying to run my `next` app with the `--turbo` flag as it drastically improves build times.
This builds the project using [Turbopack](https://turbo.build/pack). This tool is still in beta, but more than 99% of its tests are passing: https://areweturboyet.com/. I never got any issues in projects that are not using vanilla extract.

Unfortunately running `next dev --turbo` will cause the app to fail with the following error:
![image](https://github.com/vanilla-extract-css/vanilla-extract/assets/57573579/0e7a15f8-2c6e-4797-a697-66e4ed2c9a3b)

I created this simple reproduction repo, where I just ran `create-next-app` and installed vanilla extract:
https://github.com/nicolassanmar/vanilla-extract-turbopack-issue/tree/main

### Reproduction

https://github.com/nicolassanmar/vanilla-extract-turbopack-issue/tree/main

### System Info

```shell
System:
    OS: Linux 5.15 Zorin OS 16.3
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 4.26 GB / 23.27 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.13.1 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 122.0.6261.94
  npmPackages:
    @vanilla-extract/css: ^1.14.1 => 1.14.1 
    @vanilla-extract/next-plugin: ^2.3.7 => 2.3.7
```

### Used Package Manager

pnpm

### Logs

```shell
✓ Compiled / in 899ms
 ⨯ Error: Styles were unable to be assigned to a file. This is generally caused by one of the following:

- You may have created styles outside of a '.css.ts' context
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/getting-started
    at Object.getFileScope (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/@vanilla-extract+css@1.14.1/node_modules/@vanilla-extract/css/fileScope/dist/vanilla-extract-css-fileScope.cjs.dev.js:35:11)
    at generateIdentifier (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/@vanilla-extract+css@1.14.1/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js:175:49)
    at Object.style (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/@vanilla-extract+css@1.14.1/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js:374:19)
    at /home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/chunks/[root of the server]__87cd9b._.js:125:86
    at [project]/styles/vanilla-extract.css.ts [ssr] (ecmascript) (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/chunks/[root of the server]__87cd9b._.js:129:3)
    at instantiateModule (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/chunks/[turbopack]_runtime.js:488:23)
    at getOrInstantiateModuleFromParent (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/chunks/[turbopack]_runtime.js:539:12)
    at esmImport (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/chunks/[turbopack]_runtime.js:113:20)
    at /home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/chunks/[root of the server]__87cd9b._.js:141:132
    at [project]/pages/index.tsx [ssr] (ecmascript) (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/chunks/[root of the server]__87cd9b._.js:430:3)
    at instantiateModule (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/chunks/[turbopack]_runtime.js:488:23)
    at getOrInstantiateModuleFromParent (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/chunks/[turbopack]_runtime.js:539:12)
    at esmImport (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/chunks/[turbopack]_runtime.js:113:20)
    at /home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/chunks/node_modules__pnpm_af8e7b._.js:6683:112
    at [project]/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/build/templates/pages.js/(INNER_PAGE)/[project]/pages/index.tsx [ssr] (ecmascript) (ecmascript) (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/chunks/node_modules__pnpm_af8e7b._.js:6718:3)
    at instantiateModule (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/chunks/[turbopack]_runtime.js:488:23)
    at instantiateRuntimeModule (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/chunks/[turbopack]_runtime.js:547:12)
    at Object.getOrInstantiateRuntimeModule (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/chunks/[turbopack]_runtime.js:562:12)
    at Object.<anonymous> (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/.next/server/pages/index.js:6:26)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/cjs/helpers:119:18)
    at requirePage (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js:109:84)
    at /home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js:98:84
    at async loadComponentsImpl (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js:98:26)
    at async DevServer.findPageComponentsImpl (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:664:36)
    at async DevServer.findPageComponents (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:565:20)
    at async DevServer.renderPageComponent (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1832:24)
    at async DevServer.renderToResponseImpl (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1882:32)
    at async DevServer.pipeImpl (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:895:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:269:17)
    at async DevServer.handleRequestImpl (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:791:17)
    at async /home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:331:20
    at async Span.traceAsyncFn (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
    at async invokeRender (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/home/nicolassanmar/trabajo/repos/vanilla-extract-turbopack-issue/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/start-server.js:140:13) {
  page: '/'
}
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
@nicolassanmar Thanks for raising an issue. As documented in the turbopack documentation, [using webpack-based Next.js plugins as-is from next.config.js is not yet supported](https://turbo.build/pack/docs/migrating-from-webpack#webpack-loaders-and-resolve-aliases). Until we can actually write plugins for turbopack (I don't think this is possible just yet), the VE next plugin will not work with `next --turbo`.

**Comment by nicolassanmar** [comment]
@askoufis Thanks! Seems reasonable then.
It would be great if the webpack plugin got ported to turbopack.
Reading [this section](https://turbo.build/pack/docs/migrating-from-webpack#will-we-be-able-to-use-webpack-plugins) seems to indicate that they are the ones writing these plugins, and [Turbopack is not configurable yet](https://turbo.build/pack/docs/features):
> Turbopack is in beta, so very few of these decisions are set in stone. In its current state, Turbopack cannot yet be configured - so plugins are not available yet.

**Comment by askoufis** [comment]
@zecka Probably not. Webpack plugins aren't supported, [nor are they planned to be supported apparently](https://x.com/timneutkens/status/1848750086823579931). Webpack loaders can be configured, [but only a subset of webpack's loader API is available](https://nextjs.org/docs/canary/app/api-reference/config/next-config-js/turbo#configuring-webpack-loaders).

It was mentioned in [this post](https://nextjs.org/blog/turbopack-for-development-stable#what-exactly-is-stable) the Vanilla Extract doesn't work yet, but they're looking into what's required to support it, however we haven't heard anything from them about this. Maybe they're doing something on their end, who knows 🤷.

**Comment by Truimo** [comment]
I encountered the same issue and temporarily resolved it by removing Turbopack.

**Comment by nicolassanmar** [comment]
@askoufis Any news here?
It seems that [webpack loaders can be configured with turbopack](https://nextjs.org/docs/app/api-reference/turbopack#configuration) now

**Comment by AlexHartford** [comment]
With Turbopack being essentially prod-ready, it would be great to have this prioritized!

https://areweturboyet.com/
https://nextjs.org/blog/next-15-4

I've hacked together something that works, with the caveat this is **rough and should only be used for development**, but wanted to share with the hopes that maybe it helps us get to a proper solution.

`vanilla-extract-turbopack-plugin.ts`
```ts
import { createVanillaExtractPlugin } from "@vanilla-extract/next-plugin";
import type { NextConfig } from "next";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

/**
 * A Next.js plugin that adds Weback & Turbopack support for vanilla-extract.
 */
export function createVanillaExtractTurbopackPlugin(options = {}) {
  return (existingConfig: NextConfig): NextConfig => {
    // 1. Base Next.js (webpack) + vanilla-extract config
    const webpackPlugin = createVanillaExtractPlugin(options);

    // Apply the webpack plugin first to ensure compatibility with existing config
    const nextConfig = webpackPlugin(existingConfig);

    // 2. Add Turbopack rule for vanilla-extract using our custom loader
    nextConfig.turbopack = nextConfig.turbopack || {};
    const tp = nextConfig.turbopack;
    tp.rules = tp.rules || {};

    const glob = "*.css.ts";
    tp.rules[glob] = {
      // tell Turbopack to treat all .css.ts files as .ts
      as: "*.ts",
      // and run them through our vanilla-extract loader
      loaders: [
        {
		  // compile the loader manually
          loader: require.resolve("../dist/turbopack-loader.js"),
          options,
        },
      ],
    };

    return nextConfig;
  };
}
```
`turbopack-loader.ts`
```ts
import {
  getPackageInfo,
  transform,
  type IdentifierOption,
} from "@vanilla-extract/integration";
import type { LoaderContext } from "webpack";

type TurbopackLoaderOptions = {
  /** How to render class and variable identifiers */
  identifiers?: IdentifierOption;
};

/**
 * A Turbopack-compatible loader for vanilla-extract CSS.
 */
export default async function turbopackLoader(
  this: LoaderContext<TurbopackLoaderOptions>,
  source: string,
  inputSourceMap: string,
) {
  // Parse source map if provided
  let map = inputSourceMap;
  if (typeof map === "string") {
    try {
      map = JSON.parse(map);
    } catch {
      // leave original if parse fails
    }
  }

  const callback = this.async();
  try {
    const opts = this.getOptions();

    const { name: packageName } = getPackageInfo(this.rootContext);

    const identOption: IdentifierOption =
      opts.identifiers ?? (this.mode === "production" ? "short" : "debug");

    const result = await transform({
      source,
      filePath: this.resourcePath,
      rootPath: this.rootContext,
      packageName,
      identOption,
    });

    callback(null, result, map);
  } catch (err) {
    callback(err as Error);
  }
}
```

Then in `next.config.ts`, wrapping my config with this custom plugin (same as you would with the standard webpack plugin).

What this does is uses the normal webpack plugin for webpack, and this custom loader for turbopack.

With this I'm currently running Next 15.4.1, Vanilla-Extract 1.12.0 with `next dev --turbo`.

**Comment by zecka** [comment]
Thanks @AlexHartford  for your solution. It helped me a lot to get vanilla-extract working with Turbopack.

I am still seeing an issue with turbopack with style linked to Server Component. Style are not injected in <style> tag on DOM.
But I can saw component on turbopackLoader if i add some logs.

![Image](https://github.com/user-attachments/assets/42b14d1d-527d-45fc-95ec-514a33458d91)

- The same components styled with CSS Modules do not show the problem.
- If I add `"use client"` to the affected component, the styles appear, which suggests the problem is specific to SSR.
- Maybe related to: https://github.com/vercel/next.js/discussions/79500
- 
**Minimal reproduction repository**
https://github.com/zeckaissue/nextjs-15-vanilla-extract-ssr-issue

**Minimal reproduction sketch**
```tsx
// app/page.tsx (Server Component)
import { DemoServer } from '../components/Demo'; // Demo uses vanilla-extract styles
export default function Page() {
  return <DemoServer />;
}

// components/Demo.tsx
// If I put "use client" here, styles show up again in the browser.
import  {demo} from './demo.css.ts';
export function DemoServer() {
  return <div className={demo}>Hello</div>;
}

//  components/demo.css.ts
import { style } from '@vanilla-extract/css'
export const demo = style({
    backgroundColor: 'lightblue',
})

```

@AlexHartford  any suggestions here ?

**Comment by AlexHartford** [comment]
> [@AlexHartford](https://github.com/AlexHartford) any suggestions here ?

Unfortunately our project is still using pages dir, but likely will start migrating some portions of the application over to the app dir soon, so I haven't personally encountered this issue.

Could start by downgrading Next to see if it is in fact related to the issue you linked. If it's VE specific, and not a NextJS problem, I'll likely be working on something similar before too long.

**Comment by mattvagni** [comment]
If anyone is interested in taking this on as contract work, please contact me at matt plain com or on twitter (@mattvagni) and I'd be happy to sponsor you. 

We are on pages directory in our NextJS application and are blocked from upgrading NextJS due to this.

**Comment by gavinthomas-valtech** [comment]
I notice turbopack is now default bundler in next 16. Any plans to support turbopack? is it dependannt on plugin architecture of turbopack?

**Comment by zecka** [comment]
There is an open PR about turbopack support 
Check #1639 
I think @RJWadley is still working on it.

In the meantime the hack suggested by @AlexHartford  work on dev mode with some acceptable bugs.

**Comment by askoufis** [comment]
Turbopack support has been released in [v2.5.0 of the next plugin](https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract%2Fnext-plugin%402.5.0).
