### ISSUE TITLE
"module is not defined" in cssesc

### ISSUE THREAD

**Issue by jcayzac** [vanilla-extract-css/vanilla-extract#1453]
### Describe the bug

```
ReferenceError: module is not defined
    at eval (cssesc.js:110:1)
    at instantiateModule (dep-BcXSligG.js:53408:11)
```

cssesc.js is CommonJS and can't be imported as a module.

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-1kbjbz

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 148.14 MB / 36.00 GB
    Shell: 5.2.26 - /opt/homebrew/bin/bash
  Binaries:
    Node: 20.15.1 - ~/Library/pnpm/node
    npm: 10.7.0 - ~/Library/pnpm/npm
    pnpm: 9.3.0 - ~/.prefix/bin/pnpm
    bun: 1.1.17 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 126.1.67.123
    Chrome: 126.0.6478.185
    Safari: 17.5
    Safari Technology Preview: 18.0
  npmPackages:
    @vanilla-extract/css: ^1.15.3 => 1.15.3
    @vanilla-extract/vite-plugin: ^4.0.13 => 4.0.13
```

### Used Package Manager

npm

### Logs

```shell
ReferenceError: module is not defined
    at eval (cssesc.js:110:1)
    at instantiateModule (dep-BcXSligG.js:53408:11)
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jcayzac** [comment]
Original issue here: https://github.com/withastro/astro/issues/11395

**Comment by zhaohuanyuu** [comment]
I got this problem too, only appears when loading for the first time, and will be restored when reloading from [#11395](https://github.com/withastro/astro/issues/11395)

**Comment by LekoArts** [comment]
I'm also running into this error. I'm currently experimenting with the https://vitejs.dev/config/dep-optimization-options#optimizedeps-include setting, monkey-patching vanilla-extract and/or trying to adjust the Astro config. No luck so far :/

**Comment by jcayzac** [comment]
Meanwhile, I just copied cssesc.js into `overrides/cssesc/index.ts`, patched it, and added this to my `package.json`:

```json
"overrides": {
	"cssesc": "./overrides/cssesc"
}
```

This fixes it for me. I don't expect I'll need to maintain this fork, seeing the original package is dead (5+ years with no update).

**Comment by LekoArts** [comment]
Thanks for that info! I also did that now, as a workaround it'll be fine for me. If anyone from Google finds this, here's what you'll need to do:

1. Copy https://github.com/mathiasbynens/cssesc/blob/cb894eb42f27c8d3cd793f16afe35b3ab38000a1/cssesc.js into a location in your project. Also add a `package.json` that can be as minimal as e.g. like this:
		<details>
		<summary>`package.json`</summary>

		{
			"name": "cssesc",
			"version": "3.0.0",
			"description": "A JavaScript library for escaping CSS strings and identifiers while generating the shortest possible ASCII-only output.",
			"author": {
				"name": "Mathias Bynens",
				"url": "https://mathiasbynens.be/"
			},
			"license": "MIT",
			"main": "cssesc.js",
			"files": [
				"cssesc.js"
			],
			"engines": {
				"node": ">=4"
			}
		}
	</details>
2. Add the bottom of the `cssesc.js` file, change the export to: `if (typeof module === 'object') { module.exports = cssesc }`
3. If you use pnpm, add:
	```json
	"pnpm": {
		"overrides": {
			"cssesc": "./overrides/cssesc"
		}
	}
	```
3. It should "work" now

**Comment by jcayzac** [comment]
@LekoArts I just replaced the commonjs export with an esm export.

**Comment by LekoArts** [comment]
Gotcha 👍 I've updated my previous message with the instructions now that work for me both in dev and build. I just changed it to provide a dual CJS/ESM package where the `index.cjs` has the CJS export, `index.mjs` the ESM one.

**Comment by askoufis** [comment]
#1535 should fix this issue, and will be released soon hopefully. Incidentally, #1537 also fixes this issue, but I think the fix in #1535 is more targeted.

**Comment by askoufis** [comment]
@jcayzac @zhaohuanyuu @LekoArts The fix for this was released in [`@vanilla-extract/vite-plugin@4.0.20`](https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract%2Fvite-plugin%404.0.20) (via the update to [`@vanilla-extract/integration@8.0.0`](https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract%2Fintegration%408.0.0)).
