### ISSUE TITLE
#astro Vanilla Extract Build Error: "The server is being restarted or closed. Request is outdated"

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [vanilla-extract-css/vanilla-extract#1486]
### Describe the bug

I'm experiencing an issue with Vanilla Extract when trying to build my project. I've created a custom url function to help with importing images, but when I run the build process, I get an error message saying "The server is being restarted or closed. Request is outdated".

Here's an example of my code:
// url.ts
export function url(file: ImageMetadata) {
  return `url('${file.src}')`
}

// img.css.ts
import { url } from './url';
import Cater from '../path/to/Cater.png';

const s = style({
  backgroundImage: url(Cater),
})

### Reproduction

./

### System Info

```shell
System:
    OS: Linux 6.11 EndeavourOS
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1270 V2 @ 3.50GHz
    Memory: 23.61 GB / 31.31 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.9.0 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.3 - ~/DEV/QB_UNO/qb/node_modules/.bin/npm
    pnpm: 9.11.0 - /usr/bin/pnpm
    bun: 1.1.26 - ~/.bun/bin/bun
  npmPackages:
    @vanilla-extract/css: ^1.16.0 => 1.16.0 
    @vanilla-extract/css-utils: ^0.1.4 => 0.1.4 
    @vanilla-extract/dynamic: ^2.1.2 => 2.1.2 
    @vanilla-extract/vite-plugin: ^4.0.16 => 4.0.16 
    vite: ^5.4.8 => 5.4.8
```

### Used Package Manager

pnpm

### Logs

```shell
[vanilla-extract] The server is being restarted or closed. Request is outdated
file: /home/jooo/DEV/QB_UNO/qb/src/components/home/TwoColumn/img.css.ts
  Stack trace:
    at throwClosedServerError (file:///home/jooo/DEV/QB_UNO/qb/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:48792:15)
    at ModuleGraph.resolveId (file:///home/jooo/DEV/QB_UNO/qb/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:62751:29)
    at ModuleGraph.getModuleByUrl (file:///home/jooo/DEV/QB_UNO/qb/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:62322:30)
    at transformRequest (file:///home/jooo/DEV/QB_UNO/qb/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:51721:19)
    at ViteNodeServer._transformRequest (file:///home/jooo/DEV/QB_UNO/qb/node_modules/vite-node/dist/server.mjs:426:34)
    at async ViteNodeRunnerWithContext.directRequest (file:///home/jooo/DEV/QB_UNO/qb/node_modules/vite-node/dist/client.mjs:250:46)
    at async ViteNodeRunnerWithContext.dependencyRequest (file:///home/jooo/DEV/QB_UNO/qb/node_modules/vite-node/dist/client.mjs:233:12)
    at async ViteNodeRunnerWithContext.runModule (file:///home/jooo/DEV/QB_UNO/qb/node_modules/vite-node/dist/client.mjs:362:5)
    at async ViteNodeRunnerWithContext.cachedRequest (file:///home/jooo/DEV/QB_UNO/qb/node_modules/vite-node/dist/client.mjs:189:14)
    at async /home/jooo/DEV/QB_UNO/qb/node_modules/@vanilla-extract/integration/dist/vanilla-extract-integration.cjs.prod.js:807:29
    at async processQueue (/home/jooo/DEV/QB_UNO/qb/node_modules/@vanilla-extract/integration/dist/vanilla-extract-integration.cjs.prod.js:559:3)
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dojscart** [comment]
@https://github.com/jojojojojoj5564656465465 did you find the solution for this? Thanks

**Comment by masylum** [comment]
I'm facing the same problem :(

**Comment by jojojojojoj5564656465465** [comment]
Don't use file.src use the relative path instead sorry

**Comment by askoufis** [comment]
@jojojojojoj5564656465465 Did you intend to re-open this issue? It seems you have found a solution.

**Comment by jojojojojoj5564656465465** [comment]
Yes don't use import instead use `'url(public/img/a.jpg)'`

**Comment by askoufis** [comment]
> Yes don't use import instead use `'url(public/img/a.jpg)'`

In that case, should this issue be closed?

**Comment by jojojojojoj5564656465465** [comment]
yes
