### ISSUE TITLE
Monorepo with Solid Start: [nitro] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'file')

### ISSUE THREAD

**Issue by floratmin** [vanilla-extract-css/vanilla-extract#1495]
### Describe the bug

I set up a [monorepo](https://github.com/floratmin/workspace-vanilla-css-vinxi-error) with Solid (tool-app) and Solid Start (page-app) apps. The Solid App builds fine, but the Solid Start App throws an error when I try to build it with the option to prerender the page on building or throws an error when I build it without prerendering when serving.

When I remove the following lines in the file `app.config.ts` I can build:
```
prerender: {
    crawlLinks: true,
},
```

To set up the repository to make Solid Start work I set up a symlink from the page-app folder like this:

```
cd apps/page/app
ln -s ../../../node_modules/ node_modules
```

The following commands work fine:
```
nx serve tool-app
nx build tool-app
nx serve page-app
```
The following command throws an error when page should be prerendered:
```
nx build page-app
```
Building without prerendering works, but when trying to serve the built with `node apps/page/app/.output/server/index.mjs` the server throws the same error.

Setting the version of `@vanilla-extract/vite-plugin` to `4.0.10` throws `[vanilla-extract] Failed to load url` errors.

I also created an [issue](https://github.com/solidjs/solid-start/issues/1671) on the `solid-start` page.

### Reproduction

https://github.com/floratmin/workspace-vanilla-css-vinxi-error

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 14.66 GB / 30.73 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 22.8.0 - ~/.nvm/versions/node/v22.8.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v22.8.0/bin/npm
    pnpm: 9.9.0 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 130.0.6723.91
  npmPackages:
    @vanilla-extract/css: ^1.16.0 => 1.16.0 
    @vanilla-extract/recipes: ^0.5.5 => 0.5.5 
    @vanilla-extract/sprinkles: ^1.6.3 => 1.6.3 
    @vanilla-extract/vite-plugin: 4.0.17 => 4.0.17 
    rollup: 4.22.4 => 4.22.4 
    vite: 5.4.10 => 5.4.10
```

### Used Package Manager

pnpm

### Logs

```shell
⚙  Preparing app for node-server...
✔ Generated public .output/public                                               vinxi 10:06:29 AM
ℹ Initializing prerenderer                                                      vinxi 10:06:29 AM
ℹ Building Nitro Server (preset: nitro-prerender, compatibility date: ``)       vinxi 10:06:29 AM
✔ Nitro Server built                                                            vinxi 10:06:30 AM
✔ You can preview this build using npx serve .output/public                     vinxi 10:06:30 AM
ℹ Prerendering 1 initial routes with crawler                                    vinxi 10:06:30 AM
[nitro] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'file')
    at Object.get (file:///home/playground/workspace/node_modules/.pnpm/vinxi@0.4.3_@types+node@18.16.9_ioredis@5.4.1_less@4.1.3_sass@1.80.6_stylus@0.59.0_terser@5.3_pkkifnsbod3b7nmoc7jpr5cmom/node_modules/vinxi/lib/manifest/prod-server-manifest.js:168:33)
    at file:///home/playground/workspace/apps/page/app/.vinxi/prerender/chunks/nitro/nitro.mjs:1166:32
[nitro] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'file')
    at Object.get (file:///home/playground/workspace/node_modules/.pnpm/vinxi@0.4.3_@types+node@18.16.9_ioredis@5.4.1_less@4.1.3_sass@1.80.6_stylus@0.59.0_terser@5.3_pkkifnsbod3b7nmoc7jpr5cmom/node_modules/vinxi/lib/manifest/prod-server-manifest.js:168:33)
    at file:///home/playground/workspace/apps/page/app/.vinxi/prerender/chunks/nitro/nitro.mjs:1020:89
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by floratmin** [comment]
Not related to vanilla-css
