### ISSUE TITLE
Vite plugin is not extracting the styles in CSS file when used in module federation setup

### ISSUE THREAD

**Issue by smitev** [vanilla-extract-css/vanilla-extract#1506]
### Describe the bug

I have a module federation setup with Vite using [vite-plugin-federation](https://github.com/originjs/vite-plugin-federation). Also I am using **vite-tsconfig-paths**. When I try to build the apps, it doesn't compile/extract the styles in separate CSS file, instead it keeps them in JS files and when I run/preview the built app, I get this error: `Uncaught Error: Styles were unable to be assigned to a file.`

I noticed when I don't use **vite-tsconfig-paths** for the imports, the build output is correct.
I also tried to set `vanillaExtractPlugin({ unstable_mode: 'transform' })` and that one also gives the correct build output.

### Reproduction

https://github.com/smitev/vanilla-extract-vite-module-federation

### System Info

```shell
System:
    OS: macOS 14.7.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 301.97 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - /opt/homebrew/opt/node@22/bin/node
    Yarn: 4.5.1 - /opt/homebrew/opt/node@22/bin/yarn
    npm: 10.9.0 - /opt/homebrew/opt/node@22/bin/npm
  Browsers:
    Chrome: 131.0.6778.86
    Edge: 131.0.2903.51
    Safari: 18.1
```

### Used Package Manager

yarn

### Logs

```shell
Uncaught Error: Styles were unable to be assigned to a file. This is generally caused by one of the following:

- You may have created styles outside of a '.css.ts' context
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/getting-started
    at getFileScope (__federation_expose_RemoteApp-GIBzU0Fx.js:3194:11)
    at generateIdentifier (__federation_expose_RemoteApp-GIBzU0Fx.js:4980:7)
    at style (__federation_expose_RemoteApp-GIBzU0Fx.js:5047:19)
    at __federation_expose_RemoteApp-GIBzU0Fx.js:5057:19
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
I think both `vite-tsconfig-paths` and `unstable_mode: 'transform'` are red herrings. I've observed non-deterministic build output, regardless of whether or not the `tsconfigPaths` plugins is used.

Below is two builds performed one after another. One emits a CSS file, but the other doesn't. This can occur with or without the `tsconfigPaths` plugin. The CSS file is only occasionally generated. Usually it isn't generated.

<img width="718" alt="image" src="https://github.com/user-attachments/assets/c3a97d65-df29-4cbd-bb59-8559fcb2e325" />

Additionally, `unstable_mode: 'transform'` doesn't emit CSS files, so it "works", but that's because it's just loading the CSS at runtime via our [runtime adapter](https://github.com/vanilla-extract-css/vanilla-extract/blob/dde9bf2d15120e546be372390fa562384a48f99b/packages/css/src/runtimeAdapter.ts#L37), which is injected because VE is ending up bundled in the built module. This clearly isn't desirable.

I'm not sure what's causing this non-deterministic build, but for now I'm going to label this as an upstream issue and suggest you make an issue in `vite-plugin-federation`. If the maintainers of `vite-plugin-federation` can identify an issue within Vanilla Extract then we can proceed from there.

**Comment by smitev** [comment]
@askoufis thanks for checking it up.

I created issue on `vite-plugin-federation` for it.
[https://github.com/originjs/vite-plugin-federation/issues/666](https://github.com/originjs/vite-plugin-federation/issues/666)

**Comment by askoufis** [comment]
@smitev The fix for this was released in [`@vanilla-extract/vite-plugin@5.0.0`](https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract%2Fvite-plugin%405.0.0).

**Comment by smitev** [comment]
I just updated the repo to the latest dependencies (including to `@vanilla-extract/vite-plugin` **v5**), but I still see the issue.

**Comment by askoufis** [comment]
> [@askoufis](https://github.com/askoufis) I just updated the repo to the latest dependencies (including to `@vanilla-extract/vite-plugin` **v5**), but I still see the issue.

It seems like the `host` app builds correctly every time now, but the `remote` app doesn't emit any CSS. I'm still not sure what's going wrong here. It seems like there's some fundamental incompatibility between Vanilla Extract and the module federation plugin. Will keep this issue open for now.

**Comment by KevBeltrao** [comment]
I got the same issue after updating `@vanilla-extract/vite-plugin` to **v5** and I'm not using `vite-plugin-federation`.

```
plugins: [
  react(),
  tsconfigPaths(),
  vanillaExtractPlugin(),
  svgr({
    include: '**/*.svg?react',
  }),
],
```

**Comment by smitev** [comment]
hi @askoufis, I know it's busy period on your side, but did you have a chance to give it another look to this issue?

**Comment by askoufis** [comment]
@smitev I have not looked into this since last time. The upstream repo also seems rather inactive. Have you considered moving to https://github.com/module-federation/vite? It seems like a more active implementation of module federation for vite.

**Comment by smitev** [comment]
I update the reproduction repo to `vite 8` and latest `vanilla-extract` and it seems it works now, it extracts the styles in .css file.

**Comment by smitev** [comment]
Also I was considering to give it a try to [https://github.com/module-federation/vite](https://github.com/module-federation/vite). Thanks.

I will close this issue as no further action is needed.
