### ISSUE TITLE
Build errors in nextjs when dynamically importing a component that uses vanilla-extract

### ISSUE THREAD

**Issue by 5alidz** [vanilla-extract-css/vanilla-extract#618]
### Describe the bug

In a next.js app, When you dynamically import a module that is nested arbitrarily in directories, and you have `baseUrl` setup in the tsconfig it results in build error

The build error

```
web:build: Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
web:build: Error: Cannot find module 'web/../../packages/ui/theme.css.ts.vanilla.css!=!../../../../node_modules/virtual-resource-loader/dist/virtual-resource-loader.cjs.js?{"source":"OnJvb3QgewogIC0tZTliZXZjMDogcHVycGxlOwp9"}!../../../../node_modules/@vanilla-extract/webpack-plugin/extracted/dist/vanilla-extract-webpack-plugin-extracted.cjs.js'
web:build: Require stack:
web:build: - /home/khaled/projects/vanilla-extract-reproduction/apps/web/.next/server/pages/index.js
web:build: - /home/khaled/projects/vanilla-extract-reproduction/node_modules/next/dist/server/require.js
web:build: - /home/khaled/projects/vanilla-extract-reproduction/node_modules/next/dist/server/load-components.js
web:build: - /home/khaled/projects/vanilla-extract-reproduction/node_modules/next/dist/build/utils.js
web:build: - /home/khaled/projects/vanilla-extract-reproduction/node_modules/next/dist/build/worker.js
web:build: - /home/khaled/projects/vanilla-extract-reproduction/node_modules/jest-worker/build/workers/processChild.js
web:build:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
web:build:     at Function.Module._load (node:internal/modules/cjs/loader:772:27)
web:build:     at Module.require (node:internal/modules/cjs/loader:999:19)
web:build:     at require (node:internal/modules/cjs/helpers:93:18)
web:build:     at Object.638 (/home/khaled/projects/vanilla-extract-reproduction/apps/web/.next/server/pages/index.js:187:18)
web:build:     at __webpack_require__ (/home/khaled/projects/vanilla-extract-reproduction/apps/web/.next/server/webpack-runtime.js:25:42)
web:build:     at Object.0 (/home/khaled/projects/vanilla-extract-reproduction/apps/web/.next/server/chunks/0.js:36:56)
web:build:     at Function.__webpack_require__ (/home/khaled/projects/vanilla-extract-reproduction/apps/web/.next/server/webpack-runtime.js:25:42)
```

### Link to reproduction

[Link to reproduction](https://github.com/5alidz/vanilla-extract-next-dynamic-import/blob/main/apps/web/pages/index.tsx)
### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: Linux 5.10 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Memory: 1.94 GB / 5.80 GB
    Container: Yes
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 7.19.0 - ~/.nvm/versions/node/v16.4.0/bin/npm
```

**Comment by askoufis** [comment]
This issue appears to have been fixed at some point. Testing your reproduction with `@vanilla-extract/next-plugin@2.3.1` resulted in a successful build.
