### ISSUE TITLE
Undefined `sprinkles` with custom Babel configuration

### ISSUE THREAD

**Issue by simontaisne** [vanilla-extract-css/vanilla-extract#863]
### Describe the bug

Using sprinkles with latest version of `@vanilla-extract/next-plugin` and custom Babel configuration (`.babelrc`) results in error when used in Next.js project.

### Reproduction

https://github.com/simontaisne/vanilla-extract-babel-issue

### System Info

```shell
System:
  OS: macOS 12.6
  CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  Memory: 545.00 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 17.2.0 - ~/.nvm/versions/node/v17.2.0/bin/node
  Yarn: 1.22.10 - /usr/local/bin/yarn
  npm: 8.1.4 - ~/.nvm/versions/node/v17.2.0/bin/npm
Browsers:
  Chrome: 105.0.5195.125
  Firefox: 95.0.1
  Safari: 16.0
npmPackages:
  @vanilla-extract/css: 1.9.1 => 1.9.1 
  @vanilla-extract/next-plugin: 2.1.1 => 2.1.1 
  @vanilla-extract/sprinkles: 1.5.0 => 1.5.0
```

### Used Package Manager

yarn

### Logs

```shell
error - TypeError: Cannot read properties of undefined (reading 'properties')
    at eval (webpack-internal:///./components/Box/Box.tsx:34:56)
    at renderWithHooks (/Users/simontaisne/Documents/vanilla-extract-babel-issue/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderForwardRef (/Users/simontaisne/Documents/vanilla-extract-babel-issue/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5842:18)
    at renderElement (/Users/simontaisne/Documents/vanilla-extract-babel-issue/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (/Users/simontaisne/Documents/vanilla-extract-babel-issue/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/simontaisne/Documents/vanilla-extract-babel-issue/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/simontaisne/Documents/vanilla-extract-babel-issue/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/simontaisne/Documents/vanilla-extract-babel-issue/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/simontaisne/Documents/vanilla-extract-babel-issue/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/simontaisne/Documents/vanilla-extract-babel-issue/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14) {
  page: '/'
}
  21 | 
  22 |     for (const key in props) {
> 23 |       if (sprinkles.properties.has(key as keyof Sprinkles)) {
     |          ^
  24 |         atomProps[key] = props[key as keyof typeof props];
  25 |       } else {
  26 |         nativeProps[key] = props[key as keyof typeof props];
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
The fix in https://github.com/vanilla-extract-css/vanilla-extract/pull/970 fixes the error in the reproduction repo. So ensuring `@vanilla-extract/integration` is at `v6.0.3` or higher should fix the issue.
